### ISSUE TITLE
Error when argument contains a space

### ISSUE THREAD

**Issue by arharp** [jsgv/namecheap-go#1]
First of all, thanks for your work on this! I've run into what seems to be a bug, but it very well could be user error.

I'm trying to set a TXT record using something similar to the following:

`namecheap domains dns --domainname=domain.com --hostname=@ --recordtype=TXT --address="v=spf1 include:mailserver.com" --ttl=1800`

But I'm getting an error saying: `Error: expected element type <ApiResponse> but have <HTML>`

When I remove all spaces from the address argument, the command goes through. Is this a bug?

**Comment by jsgv** [comment]
@arharp Thanks for reporting this! I appreciate it. 

I can confirm this is a bug. I will create a fix and do a release as soon as I can.

I am assuming you added the correct command in your example. Should be `namecheap domains dns sethosts ...`

**Comment by jsgv** [comment]
Can you try with the latest version @arharp ? `v0.0.7`

**Comment by arharp** [comment]
@jsgv That fixed it. Thanks for the quick reply!
